---
- name: Create {{docker_compose_location}} before downlaoding docker compose
  file:
    path: "{{docker_compose_location}}"
    state: directory
    mode: "{{docker_compose_location_mode}}"

- name: Download Docker Compose
  get_url:
    url: "{{docker_compose_download_url}}"
    dest: "{{docker_compose_location}}/{{docker_compose_filename}}"
    mode: "{{docker_compose_file_mode}}"
    force: yes